# Generated by Django 5.0.6 on 2024-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrator_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Project Administrator Email'),
        ),
        migrations.AddField(
            model_name='project',
            name='administrator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project Administrator Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Cost Center'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center_description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Cost Center Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_center_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Cost Centre Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Project Duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_address',
            field=models.TextField(blank=True, verbose_name='Project Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reception_telephone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reception Telephone'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Project Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('IP', 'In-Progress'), ('CP', 'Completed')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Value'),
        ),
    ]
