# Generated by Django 5.0.6 on 2024-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_administrator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='administrator_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Administrator Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='administrator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Administrator Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
    ]
