# Generated by Django 5.0.6 on 2024-06-06 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_by_alter_project_start_date'),
        ('tasks', '0003_alter_task_name'),
        ('time_tracker', '0002_alter_timetracker_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_by_timeline_user_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_project_model', to='projects.project'),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approve'), ('RJ', 'Reject')], default='PD', max_length=2),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
